filesets:
    includes:
        - README.md
    excludes:
        - \.git
        - .gobuild.yml
        - ngrokd.go
settings:
        build: |
            if test "$GOOS" = "windows" -a "$GOARCH" = "386"
            then
                go install -v -tags 'release'
            else
                go install -v -tags 'release'
            fi